# SetForge Configuration File
# ==========================
# This file centralizes all configuration for the SetForge data pipelines.

# API Provider Configuration
# --------------------------
# List all API providers you intend to use.
# The manager will rotate through them, prioritizing paid tiers.
#
# - name: A unique identifier for this client.
# - provider: 'vertex_ai' or 'google_ai_studio'.
# - model: The specific model name (e.g., 'gemini-1.5-pro-preview-0409').
# - api_key: Your API key (required for google_ai_studio).
# - project_id: Your Google Cloud Project ID (required for vertex_ai).
# - tier: 'paid' or 'free'. Paid tiers are always prioritized.
# - rpm: Requests Per Minute limit for this key.
# - tpm: Tokens Per Minute limit for this key.

api_providers:
  - name: "studio_tier_1"
    provider: "google_ai_studio"
    model: "gemini-2.5-flash"
    api_key: "AIzaSyCyqyWa2cs3zSlA5_E8Zpd4AmImx6BjF4E"
    tier: "paid"
    rpm: 4000
    tpm: 4000000
  - name: "studio_free_1"
    provider: "google_ai_studio"
    model: "gemini-2.0-flash"
    api_key: "AIzaSyDoKaA40vv5yzY6cMlUEEtnvr2toqNkAQw"
    tier: "free"
    rpm: 15
    tpm: 250000
  - name: "studio_free_2"
    provider: "google_ai_studio"
    model: "gemini-2.0-flash"
    api_key: "AIzaSyAX5JUyfbeub1JqtqxLiD1mYh--YCDo0d4"
    tier: "free"
    rpm: 15
    tpm: 1000000
  - name: "studio_free_3"
    provider: "google_ai_studio"
    model: "gemini-2.0-flash"
    api_key: "AIzaSyD42IyyLhXjDfGxbPoBIiYjxEKc9G0oVuw"
    tier: "free"
    rpm: 15
    tpm: 1000000
  - name: "studio_free_4"
    provider: "google_ai_studio"
    model: "gemini-2.0-flash"
    api_key: "AIzaSyDHg970Phhe0-XpnHF-JE7LvVMvWbewbgA"
    tier: "free"
    rpm: 15
    tpm: 1000000
  - name: "studio_free_5"
    provider: "google_ai_studio"
    model: "gemini-2.0-flash"
    api_key: "AIzaSyAULhy8yjyMkmfr0asR80raT_a9cvE-fgE"
    tier: "free"
    rpm: 15
    tpm: 1000000
  - name: "studio_free_6"
    provider: "google_ai_studio"
    model: "gemini-2.0-flash"
    api_key: "AIzaSyAfw7X1BmuNKfvS5sPQrSaIOuPdZN7N_RM"
    tier: "free"
    rpm: 15
    tpm: 1000000
  - name: "studio_free_7"
    provider: "google_ai_studio"
    model: "gemini-2.0-flash"
    api_key: "AIzaSyC1qsGypvfWfG9-iR34lHxb0SG-osFFpJk"
    tier: "free"
    rpm: 15
    tpm: 1000000
  - name: "studio_free_8"
    provider: "google_ai_studio"
    model: "gemini-2.0-flash"
    api_key: "AIzaSyDKFCi31oUBMzd-Zd_JZ5CQWF65olGf-c4"
    tier: "free"
    rpm: 15
    tpm: 1000000

# Data Pipeline Configuration
# ---------------------------
# Defines the directory structure for the data processing pipelines.
data_config:
  raw_dir: "data_raw"
  cleaned_dir: "data_cleaned"
  structured_dir: "data_structured"
  qa_dir: "data_qa"
  log_dir: "logs"
  checkpoint_dir: "checkpoints"

# Web Scraper Configuration
# -------------------------
scraper_config:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
  timeout: 30 # seconds
  max_depth: 5 # Maximum recursion depth for crawling
  max_files_per_domain: 100 # Safety limit for number of files per domain

# Q&A Generation Pipeline Configuration
# -------------------------------------
qa_pipeline_config:
  concurrency_limit: 5      # Max number of files to process at the same time
  max_retries: 3            # Retries for a file before it's considered failed
  dead_letter_queue_dir: "data/dead_letter_queue/qa" # Folder for failed files
  qa_output_file: "data_qa/qna_dataset.jsonl"       # Main dataset output
  qa_review_file: "data_qa/needs_review.jsonl"     # Output for Q&A pairs that fail validation
