# src/components/faiss.pyi
from typing import Any, Tuple
import numpy as np

class Index:
    ntotal: int
    def __init__(self, d: int, metric: Any = None) -> None: ...
    def add(self, x: np.ndarray[Any, Any]) -> None: ...
    def search(self, x: np.ndarray[Any, Any], k: int) -> Tuple[np.ndarray[Any, Any], np.ndarray[Any, Any]]: ...

def read_index(filepath: str) -> Index: ...
def write_index(index: Index, filepath: str) -> None: ...

class IndexFlatL2(Index): ...
