import re

class TextPreprocessor:
    def __init__(self):
        pass

    def preprocess(self, text: str) -> str:
        """
        Cleans the input text by removing boilerplate and other irrelevant information.
        """
        # Remove header and footer boilerplate
        text = re.sub(r'• Programme \d{4}-\d{2}', '', text)
        text = re.sub(r'• School of.*', '', text)
        text = re.sub(r'Examination Annual Report', '', text)
        text = re.sub(r'Academic Bank of Credits \(ABC\)', '', text)
        text = re.sub(r'Curricula Feedback', '', text)
        text = re.sub(r'University Brochure', '', text)
        text = re.sub(r'• Programme Fee', '', text)
        text = re.sub(r'• Hostel Fee', '', text)
        text = re.sub(r'• Transportation Fee', '', text)
        text = re.sub(r'• Scholarship', '', text)
        text = re.sub(r'• Innovative Idea Scholarship', '', text)
        text = re.sub(r'• Fee Structure for Previous Year Students', '', text)
        text = re.sub(r'• SUAT \d{4}', '', text)
        text = re.sub(r'Sample Papers', '', text)
        text = re.sub(r'• Sample Papers', '', text)
        text = re.sub(r'Global Knowledge Seekers', '', text)
        text = re.sub(r'• Global Knowledge Seekers', '', text)
        text = re.sub(r'Our Recruiters', '', text)
        text = re.sub(r'• Our Recruiters', '', text)
        text = re.sub(r'Banking And Postal Services', '', text)
        text = re.sub(r'• Banking And Postal Services', '', text)
        text = re.sub(r'Perspective Plan', '', text)
        text = re.sub(r'Leadership', '', text)
        text = re.sub(r'History', '', text)
        text = re.sub(r'Statutory Bodies of the University', '', text)
        text = re.sub(r'Sharda Tenders', '', text)
        text = re.sub(r'Act, Statutes and Ordinances', '', text)
        text = re.sub(r'COVID19', '', text)
        text = re.sub(r'Family & Couple Counselling Services\(FCCS\)', '', text)
        text = re.sub(r'Capacity Development & Skill Enhancement', '', text)
        text = re.sub(r'Language and Communication Skill Initiatives: Sharda Skills', '', text)
        text = re.sub(r'Soft Skill Initiatives : Career Counseling and Development Center', '', text)
        text = re.sub(r'Awareness of Trends in Technology : IIC', '', text)
        text = re.sub(r'Entrepreneurship', '', text)
        text = re.sub(r'Innovation and Entrepreneurship', '', text)
        text = re.sub(r'• Get to know sharda', '', text)
        text = re.sub(r'• Perspective Plan', '', text)
        text = re.sub(r'• Leadership', '', text)
        text = re.sub(r'• History', '', text)
        text = re.sub(r'• Statutory Bodies of the University', '', text)
        text = re.sub(r'• Sharda Tenders', '', text)
        text = re.sub(r'• Act, Statutes and Ordinances', '', text)
        text = re.sub(r'• COVID19', '', text)
        text = re.sub(r'• Family & Couple Counselling Services\(FCCS\)', '', text)
        text = re.sub(r'• Capacity Development & Skill Enhancement', '', text)
        text = re.sub(r'• Language and Communication Skill Initiatives: Sharda Skills', '', text)
        text = re.sub(r'• Soft Skill Initiatives : Career Counseling and Development Center', '', text)
        text = re.sub(r'• Awareness of Trends in Technology : IIC', '', text)
        text = re.sub(r'• Entrepreneurship', '', text)
        text = re.sub(r'• Innovation and Entrepreneurship', '', text)
        text = re.sub(r'FM Radio: Suno Sharda-90.8FM', '', text)
        text = re.sub(r'• FM Radio: Suno Sharda-90.8FM', '', text)
        text = re.sub(r'Accommodation Fee', '', text)
        text = re.sub(r'Guidelines for Visa and FRO/FRRO', '', text)
        text = re.sub(r'Guidelines for Medical Insurance', '', text)
        text = re.sub(r'Observership Programmes', '', text)
        text = re.sub(r'• Accommodation Fee', '', text)
        text = re.sub(r'• Guidelines for Visa and FRO/FRRO', '', text)
        text = re.sub(r'• Guidelines for Medical Insurance', '', text)
        text = re.sub(r'• Observership Programmes', '', text)
        text = re.sub(r'Paramarsh- Our Mentoring Portal', '', text)
        text = re.sub(r'• Paramarsh- Our Mentoring Portal', '', text)
        text = re.sub(r'• Recruiters', '', text)
        text = re.sub(r'• Covid 19 Updates', '', text)
        text = re.sub(r'• Sharda University Uzbekistan', '', text)
        text = re.sub(r'• Sharda University Agra', '', text)
        text = re.sub(r'• Courses on Human Values and Professional ethics', '', text)
        text = re.sub(r'• National Cyber Crime Reporting Portal', '', text)
        text = re.sub(r'• International Credit Transfer Programme', '', text)
        text = re.sub(r'\+91-\d{10}', '', text)
        text = re.sub(r'\+91-\d{5}-\d{5}', '', text)
        text = re.sub(r'\d{8}', '', text)

        # Remove extra whitespace
        text = '\n'.join([line.strip() for line in text.split('\n') if line.strip()])

        return text
